"""Small database boundary: SQLite locally, PostgreSQL when DATABASE_URL is set.

Only application-authored SQL crosses this boundary. Values always remain bound
parameters. PostgreSQL transactions use transaction-scoped advisory locks for
the operations that require the same serialization as SQLite BEGIN IMMEDIATE.
"""
from contextlib import contextmanager
import os
import re
import sqlite3

import psycopg

INTEGRITY_ERRORS = (sqlite3.IntegrityError, psycopg.IntegrityError)
WRITE_LOCK = 187336201


class Row(dict):
    """Named columns with positional access for existing aggregate queries."""
    def __getitem__(self, key):
        if isinstance(key, int):
            return tuple(self.values())[key]
        return super().__getitem__(key)


def row_factory(cursor):
    names = [column.name for column in cursor.description] if cursor.description else []
    return lambda values: Row(zip(names, values))


def postgres_query(query):
    # Preserve quoted SQL literals/identifiers, including escaped quotes. The
    # application's SQL contains no comments, dollar quotes or JSON operators.
    tokens = re.split(r"('(?:[^']|'')*'|\"(?:[^\"]|\"\")*\")", query)
    return ''.join(part.replace('%', '%%') if i % 2 else part.replace('%', '%%').replace('?', '%s')
                   for i, part in enumerate(tokens))


class PostgresConnection:
    dialect = 'postgres'

    def __init__(self, connection):
        self.connection = connection

    def execute(self, query, parameters=None):
        if parameters is None:
            return self.connection.execute(query)
        return self.connection.execute(postgres_query(query), parameters)

    def executemany(self, query, parameters):
        cursor = self.connection.cursor()
        cursor.executemany(postgres_query(query), parameters)
        return cursor


def write_lock(conn):
    if getattr(conn, 'dialect', 'sqlite') == 'postgres':
        conn.execute('SELECT pg_advisory_xact_lock(?)', (WRITE_LOCK,))
    else:
        conn.execute('BEGIN IMMEDIATE')


def photo_columns(conn):
    if getattr(conn, 'dialect', 'sqlite') == 'postgres':
        return {row[0] for row in conn.execute("SELECT column_name FROM information_schema.columns WHERE table_schema=current_schema() AND table_name='photos'")}
    return {row['name'] for row in conn.execute('PRAGMA table_info(photos)')}


class Database:
    def __init__(self, path):
        self.path = path
        self.url = os.environ.get('DATABASE_URL', '').strip()
        self.backend = 'postgres' if self.url else 'sqlite'
        if self.url and not self.url.startswith(('postgresql://', 'postgres://')):
            raise ValueError('DATABASE_URL must be a PostgreSQL connection URL.')
        if os.environ.get('RENDER') == 'true':
            if not self.url:
                raise ValueError('Render requires DATABASE_URL. SQLite on the local disk is not persistent.')
            if os.environ.get('EW_PHOTO_STORAGE', 'local') != 'r2':
                raise ValueError('Render requires EW_PHOTO_STORAGE=r2 to preserve uploaded photos.')

    @contextmanager
    def __call__(self):
        if self.backend == 'postgres':
            try:
                conn = psycopg.connect(self.url, connect_timeout=15, row_factory=row_factory,
                                       prepare_threshold=None)
            except psycopg.Error:
                raise RuntimeError('Cannot connect to PostgreSQL. Check DATABASE_URL in your hosting settings.') from None
            with conn:
                conn.execute("SET LOCAL statement_timeout = '20s'")
                conn.execute("SET LOCAL lock_timeout = '15s'")
                yield PostgresConnection(conn)
        else:
            conn = sqlite3.connect(self.path, timeout=20)
            conn.row_factory = sqlite3.Row
            conn.execute('PRAGMA foreign_keys=ON')
            conn.execute('PRAGMA busy_timeout=20000')
            try:
                with conn:
                    yield conn
            finally:
                conn.close()

    def initialize(self, schema, migrate_roles, store, setup_file):
        if self.backend == 'sqlite':
            with self() as conn:
                conn.execute('PRAGMA journal_mode=WAL')
                conn.executescript(schema)
                migrate_roles(conn, store)
            if not setup_file.exists():
                import secrets
                try:
                    fd = os.open(setup_file, os.O_CREAT | os.O_EXCL | os.O_WRONLY, 0o600)
                    with os.fdopen(fd, 'w') as file:
                        file.write(secrets.token_urlsafe(32))
                except FileExistsError:
                    pass
            return setup_file.read_text().strip()

        import secrets
        schema = schema.replace('INTEGER PRIMARY KEY AUTOINCREMENT', 'INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY')
        schema = re.sub(r'\bREAL\b', 'DOUBLE PRECISION', schema)
        with self() as conn:
            write_lock(conn)
            for statement in schema.split(';'):
                if statement.strip():
                    conn.execute(statement)
            conn.execute('CREATE TABLE IF NOT EXISTS app_settings (key TEXT PRIMARY KEY, value TEXT NOT NULL)')
            conn.execute("INSERT INTO app_settings(key,value) VALUES ('setup_token',?) ON CONFLICT(key) DO NOTHING", (secrets.token_urlsafe(32),))
            return conn.execute("SELECT value FROM app_settings WHERE key='setup_token'").fetchone()[0]
