-- Applied to Supabase project kiuvljeudopvaumkkrrd as version 20261008235853.
-- The FastAPI server is the only data access layer. Keeping application tables
-- outside `public` prevents Supabase Data API exposure and makes the existing
-- three-role authorization model authoritative.
create schema if not exists app_private;
revoke all on schema app_private from public;
revoke all on schema app_private from anon, authenticated;

create table if not exists app_private.users (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null unique,
  password_hash text not null,
  role text not null check (role in ('admin', 'technician', 'requester')),
  active integer not null default 1 check (active in (0, 1)),
  must_change integer not null default 0 check (must_change in (0, 1)),
  created_at text not null
);

create table if not exists app_private.sessions (
  token_hash text primary key,
  user_id bigint references app_private.users(id),
  csrf text not null,
  expires double precision not null
);

create table if not exists app_private.attempts (
  key text primary key,
  count integer not null,
  first_at double precision not null
);

create table if not exists app_private.jobs (
  id bigint generated by default as identity primary key,
  title text not null,
  description text not null default '',
  unit text not null default '',
  location text not null default '',
  category text not null,
  priority text not null,
  status text not null,
  assignee_id bigint references app_private.users(id),
  due_date text not null default '',
  created_by bigint not null references app_private.users(id),
  created_at text not null,
  updated_at text not null,
  completed_at text,
  archived integer not null default 0 check (archived in (0, 1)),
  version integer not null default 1
);

create table if not exists app_private.photos (
  id bigint generated by default as identity primary key,
  job_id bigint not null references app_private.jobs(id),
  filename text not null unique,
  original_name text not null,
  phase text not null,
  caption text not null default '',
  uploaded_by bigint not null references app_private.users(id),
  created_at text not null
);

create table if not exists app_private.activity (
  id bigint generated by default as identity primary key,
  job_id bigint not null references app_private.jobs(id),
  user_id bigint not null references app_private.users(id),
  kind text not null,
  body text not null,
  created_at text not null
);

create table if not exists app_private.notifications (
  id bigint generated by default as identity primary key,
  user_id bigint not null references app_private.users(id),
  job_id bigint references app_private.jobs(id),
  body text not null,
  seen integer not null default 0 check (seen in (0, 1)),
  created_at text not null
);

create index if not exists jobs_assignee on app_private.jobs(assignee_id);
create index if not exists jobs_creator on app_private.jobs(created_by);
create index if not exists activity_job on app_private.activity(job_id);
create index if not exists photos_job on app_private.photos(job_id);
create index if not exists notifications_user on app_private.notifications(user_id, seen);
create index if not exists sessions_expiry on app_private.sessions(expires);

-- Defense in depth: no browser role may access application records. FastAPI
-- connects as the table owner and enforces its own three-role access model.
alter table app_private.users enable row level security;
alter table app_private.sessions enable row level security;
alter table app_private.attempts enable row level security;
alter table app_private.jobs enable row level security;
alter table app_private.photos enable row level security;
alter table app_private.activity enable row level security;
alter table app_private.notifications enable row level security;
revoke all on all tables in schema app_private from public, anon, authenticated;
revoke all on all sequences in schema app_private from public, anon, authenticated;
